name: Feature Enhancement
description: Suggest an idea for this project
title: "[Feature]: *Use a clear and descriptive title for the issue to identify the suggestion.*"
labels: [enhancement]
body:
- type: textarea
  id: description
  attributes:
    label: Describe the suggested Enhancement
    description: "Provide a step-by-step description of the suggested enhancement in as many details as possible."
    placeholder: "Enhancement description"
  validations:
    required: true
- type: textarea
  id: example
  attributes:
    label: Example
    description: "Provide specific examples to demonstrate the steps that you imagine you would take if the feature you're requesting will be implemented."
    placeholder: "Code example or detailed description to demonstrate the steps."
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: "Description of expected behavior"
    placeholder: "A clear and concise description of what you expect to happen."
  validations:
    required: true
- type: textarea
  id: justification
  attributes:
    label: Justification
    description: "Explain why this enhancement would be useful to most Relativity.Testing.Framework users."
    placeholder: "How will this Enhancement be useful to Relativity.Testing.Framework users?"
  validations:
    required: true
