name: 'Test Report'
on:
  workflow_run:
    workflows: ['FeatureBranch', 'ReleaseBranch']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Unit Test Report
      uses: dorny/test-reporter@v1.5.0
      with:
        artifact: Logs
        name: Unit Test Report
        path: '*.TestResults.trx'
        reporter: dotnet-trx
    - name: Functional Test Report
      uses: dorny/test-reporter@v1.5.0
      with:
        artifact: FunctionalTestLogs
        name: Functional Test Report
        path: 'functional-test/*.TestResults.trx'
        reporter: dotnet-trx